# Generated by Django 2.2.4 on 2019-08-23 03:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=20, verbose_name='滚动字幕')),
                ('color', models.CharField(max_length=20, verbose_name='字体颜色')),
            ],
            options={
                'verbose_name': '轮播表',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='小说分类')),
            ],
            options={
                'verbose_name': '标题表',
            },
        ),
        migrations.CreateModel(
            name='NovelUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pen_name', models.CharField(max_length=16, verbose_name='笔名/用户名')),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=12, verbose_name='真实姓名')),
                ('email', models.CharField(max_length=20, null=True)),
            ],
            options={
                'verbose_name': '用户表',
            },
        ),
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('content', models.TextField(max_length=65530, verbose_name='正文')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创作时间')),
                ('read_times', models.IntegerField(default=0, verbose_name='阅读次数')),
                ('level', models.IntegerField(verbose_name='小说等级，对2求余分5等')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Novel.Menu', verbose_name='关联大分类标题')),
                ('novel_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Novel.NovelUser', verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '小说表',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200, verbose_name='评论内容')),
                ('novel', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Novel.Novel', verbose_name='关联小说')),
                ('novel_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Novel.NovelUser', verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '评论表',
            },
        ),
    ]
